# Theme Info
theme_name: ILS

theme_version: 0.1.1

menu:
  Home: /
  Archives: /archives
  About: /about

rss: /atom.xml

favicon: images/favicon.png

avatar: images/avatar.png

# Site page layout setting.
page:
  left_side_width: 30
  right_side_width: 70
  media_max_width: 960

# Social Links.
# Usage: `Key: permalink || icon`
# Key is the link label showing to end users.
# Value before `||` delimeter is the target permalink.
# Value after `||` delimeter is the name of FontAwesome icon.
social:
  #GitHub: https://github.com/yourname || github
  #E-Mail: mailto:yourmail || envelope
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #Weibo: https://www.facebook.com/yourname || weibo
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #Instagram: https://instagram.com/yourname || instagram

# Code Highlight theme
# Available value:
#   normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://github.com/xCss/Valine
valine:
  enable: true
  appid:  ih2nzG3ilVNdLgJK4kBXTjOq-gzGzoHsz # your leancloud application appid
  appkey: gdf6tXXLBTLg9qpjS2y6Tbw7 # your leancloud application appkey
  notify: false # mail notifier, https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 评论一下再走吧~

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: false
  # custom uv span for the whole site
  site_uv: false
  site_uv_header:
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: false
  site_pv_header:
  site_pv_footer:
  # custom pv span for one page only
  page_pv: false
  page_pv_header:
  page_pv_footer:

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: false
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false


# Assets
css: css
js: js
images: images