on:
  push:
    branches:
      - master

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[
            {
              "type": "feat",
              "section": "ğŸŒŸ Features",
              "hidden": false
            },
            {
              "type": "fix",
              "section": "ğŸ Bug Fixes",
              "hidden": false
            },
            {
              "type": "docs",
              "section": "ğŸ“– Docs",
              "hidden": false
            },
            {
              "type": "style",
              "section": "ğŸ¨ Styling",
              "hidden": false
            },
            {
              "type": "refactor",
              "section": "ğŸ­ Code Refactoring",
              "hidden": false
            },
            {
              "type": "perf",
              "section": "ğŸ›  Performance Improvements",
              "hidden": false
            },
            {
              "type": "test",
              "section": "ğŸš§ Tests",
              "hidden": false
            },
            {
              "type": "build",
              "section": "ğŸ“¦ Build System",
              "hidden": false
            },
            {
              "type": "revert",
              "section": "ğŸŒ€ Reverts",
              "hidden": false
            },
            {
              "type": "ci",
              "section": "ğŸ¯ CI",
              "hidden": false
            },
            {
              "type": "ui",
              "section": "ğŸ’„ Improvement UI",
              "hidden": false
            },
            {
              "type": "chore",
              "section": "ğŸš¦ Chore",
              "hidden": false
            }
          ]'

      # The logic below handles the npm publication

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
        if: ${{ steps.release.outputs.release_created }}

      - run: npm install
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
