on:
  push:
    branches:
      - master

name: release-version

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[
            {"type": "types", "section": "Types", "hidden": false},
            {"type": "revert", "section": "Reverts", "hidden": false},
            {"type": "feat", "section": "Features", "hidden": false},
            {"type": "fix", "section": "Bug Fixes", "hidden": false},
            {"type": "improvement", "section": "Feature Improvements", "hidden": false},
            {"type": "docs", "section": "Docs", "hidden": false},
            {"type": "style", "section": "Styling", "hidden": false},
            {"type": "refactor", "section": "Code Refactoring", "hidden": false},
            {"type": "perf", "section": "Performance Improvements", "hidden": false},
            {"type": "test", "section": "Tests", "hidden": false},
            {"type": "build", "section": "Build System", "hidden": false},
            {"type": "ci", "section":"CI", "hidden": false}
          ]'

      # The logic below handles the npm publication

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
        if: ${{ steps.release.outputs.release_created }}

      - run: npm install
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
